version: '3.8'

services:
  # Servicio para el contenedor de la API
  eventop:
    container_name: eventop  # Nombre del contenedor
    image: eventop  # Imagen del contenedor (la misma que el nombre)
    ports:
      - "3000:3000"  # Exponer el puerto 3000 del contenedor
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresdb:5432/eventop  # URL de conexión a la DB
    depends_on:
      - postgresdb  # El contenedor de la API depende del contenedor de la DB
    restart: always  # Reinicia el contenedor si falla
    networks:
      - eventop_network  # Aseguramos que los contenedores estén en la misma red

  # Servicio para el contenedor de PostgreSQL
  postgresdb:
    container_name: postgresdb  # Nombre del contenedor de la base de datos
    image: postgres  # Imagen de PostgreSQL
    environment:
      POSTGRES_USER: postgres  # Usuario de la base de datos
      POSTGRES_PASSWORD: postgres  # Contraseña de la base de datos
      POSTGRES_DB: eventop  # Nombre de la base de datos
    ports:
      - "5432:5432"  # Exponer el puerto 5432 para la conexión a la DB
    restart: always  # Reinicia el contenedor si falla
    networks:
      - eventop_network  # Aseguramos que los contenedores estén en la misma red

networks:
  eventop_network:  # Red personalizada para la comunicación entre contenedores
    driver: bridge
