import IEventos from "@/interfaces/IEventos";

export const Events: IEventos[] = [
    {
      eventId: 1,
      name: "Rock Fest",
      description: "Festival nacional de rock 2024",
      date: "21/12/2024",
      price: 15000,
      currency: "pesos",
      locationId: 1,
      categoryId: 1,
    
    },
    {
      eventId: 2,
      name: "Jazz Under the Stars",
      description: "Concierto de jazz al aire libre en la plaza central",
      date: "10/01/2025",
      price: 12000,
      currency: "pesos",
      locationId: 2,
      categoryId: 2,
    },
    {
      eventId: 3,
      name: "Tech Conference 2024",
      description: "Conferencia de tecnología con expertos internacionales",
      date: "15/02/2025",
      price: 25000,
      currency: "pesos",
      locationId: 3,
      categoryId: 3,
    },
    {
      eventId: 4,
      name: "Food & Wine Fest",
      description: "Feria de vinos y gastronomía gourmet",
      date: "18/03/2025",
      price: 30000,
      currency: "pesos",
      locationId: 4,
      categoryId: 4,
    },
    {
      eventId: 5,
      name: "Open Air Cinema",
      description: "Proyección de películas clásicas en el parque",
      date: "25/04/2025",
      price: 5000,
      currency: "pesos",
      locationId: 5,
      categoryId: 5,
    },
    {
      eventId: 6,
      name: "Techno Party",
      description: "Fiesta electrónica en un club exclusivo",
      date: "30/05/2025",
      price: 10000,
      currency: "pesos",
      locationId: 1,
      categoryId: 1,
    },
    {
      eventId: 7,
      name: "Medieval Festival",
      description: "Festival medieval con mercados, batallas y shows",
      date: "14/06/2025",
      price: 20000,
      currency: "pesos",
      locationId: 2,
      categoryId: 2,
    },
    {
      eventId: 8,
      name: "Yoga Retreat",
      description: "Retiro de yoga en la naturaleza para todos los niveles",
      date: "20/07/2025",
      price: 18000,
      currency: "pesos",
      locationId: 3,
      categoryId: 3,
    },
    {
      eventId: 9,
      name: "Rock Concert: Legends Tour",
      description: "Concierto de rock con bandas clásicas en vivo",
      date: "05/08/2025",
      price: 22000,
      currency: "pesos",
      locationId: 4,
      categoryId: 4,
    },
    {
      eventId: 10,
      name: "Art Expo 2025",
      description: "Exposición de arte contemporáneo con artistas internacionales",
      date: "12/09/2025",
      price: 15000,
      currency: "pesos",
      locationId: 5,
      categoryId: 5,
    },
  ];
  
  export default Events;
  